spring:
  datasource:
    url: jdbc:mysql://localhost:3307/TaskManagementSystem?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate  # Только проверка, без изменений
  flyway:
    enabled: true
    locations: classpath:db/migration
jwt:
  secret: 78123612387123891asdasdasd81238912398
  lifetime: 30m
springdoc:
    swagger-ui:
      enabled: true
      title: Todo Management API
      description: API для управления задачами
      path: /swagger-ui.html
responses:
  '200':
    description: Task found
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/TodoResponseDto'
  '404':
    description: Task not found
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/ErrorResponse'
ErrorResponse:
  type: object
  properties:
    error:
      type: string
    message:
      type: string