version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: task_management_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TaskManagementSystem
    ports:
      - "3310:3310"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - app-network

  app:
    image: achiro124/taskmanagementsystem-app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_management_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/TaskManagementSystem?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: true
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      JWT_SECRET: 78123612387123891asdasdasd81238912398
      JWT_LIFETIME: 30m
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge